# -*- coding: utf-8 -*-
"""PCA fpr dimentionality reduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gxHKTRxJ4T4n8_EsmTulxNJPhU-U2RiX
"""



"""## Step-1: Import necessary libraries"""

# Import necessary libraries
from sklearn import datasets  # to retrieve the iris Dataset
import pandas as pd  # to load the dataframe
from sklearn.preprocessing import StandardScaler  # to standardize the features
from sklearn.decomposition import PCA  # to apply PCA
import seaborn as sns  # to plot the heat maps



"""## Step-2: Load the dataset"""

#Load the Dataset
iris = datasets.load_iris()
#convert the dataset into a pandas data frame
df = pd.DataFrame(iris['data'], columns = iris['feature_names'])
#display the head (first 5 rows) of the dataset
df.head()



"""## Step-3: Standardize the features"""

#Standardize the features
#Create an object of StandardScaler which is present in sklearn.preprocessing
scalar = StandardScaler()
scaled_data = pd.DataFrame(scalar.fit_transform(df)) #scaling the data
scaled_data



"""## Step-3: Check the Co-relation between features without PCA (Optional)"""

#Check the Co-relation between features without PCA
sns.heatmap(scaled_data.corr())



"""## Step-4: Applying Principal Component Analysis"""

#Applying PCA
#Taking no. of Principal Components as 3
pca = PCA(n_components = 3)
pca.fit(scaled_data)
data_pca = pca.transform(scaled_data)
data_pca = pd.DataFrame(data_pca,columns=['PC1','PC2','PC3'])
data_pca.head()



"""## Step-5: Checking Co-relation between features after PCA"""

#Checking Co-relation between features after PCA
sns.heatmap(data_pca.corr())

